### ISSUE TITLE
Should RiderScriptEditorDataPersisted be committed?

### ISSUE THREAD

**Issue by adarapata** [van800/com.unity.ide.rider#15]
Hi :)
I have a question about a problem I am having.

I have just updated my rider package.
`RiderScriptEditorDataPersisted.asset` is generated and frequently diffs to `lastWriteTimeTicks.`

Should this file be shared with the project?

**Comment by van800** [comment]
Please add it to gitignore.
I have already made a change for the next package version to store it in Library folder.
Sorry for the inconvenience.

**Comment by adarapata** [comment]
thanks!

**Comment by van800** [comment]
Updated package can be used even prior to release on the Unity package registry.

To use the github version, just update manifest.json, substitute
"com.unity.ide.rider": "3.0.13",
by
"com.unity.ide.rider": "https://github.com/van800/com.unity.ide.rider.git?path=/Packages/com.unity.ide.rider#3.0.14",
