### ISSUE TITLE
-nullable in csc.rsp doesn't work with +/- suffices

### ISSUE THREAD

**Issue by andersljungberg** [van800/com.unity.ide.rider#7]
The following line: 

https://github.com/van800/com.unity.ide.rider/blob/24806b291373d9e65c9075c191f2bd9d77a47373/Packages/com.unity.ide.rider/Rider/Editor/ProjectGeneration/ProjectGeneration.cs#L742

is making an Equal comparison instead of StartsWith. So the following foreach

https://github.com/van800/com.unity.ide.rider/blob/bcaa3df96664f70c78adb37bd33a76f740616853/Packages/com.unity.ide.rider/Rider/Editor/ProjectGeneration/ProjectGeneration.cs#L533

doesn't do anything. Works for us since we are opting in, but I guess if someone wants to enable nullable for the entire project and then opt out it won't work.

Thanks for great work btw. =)

**Comment by LegoCylon** [comment]
As a workaround, you can use -nullable:enable and both Unity and Rider handle this correctly.

**Comment by van800** [comment]
Thank you for reporting. Fixed in https://github.com/van800/com.unity.ide.rider/commit/11492dda5cc797f1ac7a81a0a2ff079f46962f92
Targets package version 3.0.7, expected to be published within a month or two.
