### ISSUE TITLE
Unity and Rider connection not working

### ISSUE THREAD

**Issue by ziomek64** [van800/com.unity.ide.rider#8]
As in the title Rider can't connect with Unity. I have newest package, tried different versions. It happened to me after I updated Rider, although i tried reinstalling and removing anything related to JetBrains from PC. Still not working. How do I actually make sure I connect Rider with Unity? It's such a random thing, I barely made it work last time, it was pure luck. On top of that there is this langversion that is wrong or something when compiling.

**Comment by van800** [comment]
Hi! Please report in Rider with `Help->Report a Bug`, agree to attach logs. One first thing to check, which I can suggest - make sure External Editor in Unity points to correct Rider version.
![image](https://user-images.githubusercontent.com/1482681/119779484-06663e80-bec9-11eb-85a9-bb576360cd05.png)
